preset: laravel

risky: false

enabled:
  - align_double_arrow
  - align_equals
  - phpdoc_order
  - phpdoc_separation

disabled:
  - unalign_equals

finder:
  name:
    - "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"
  exclude:
    - "public"
    - "tests"
